/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistes;
import Domini.Controlador.ControladorDomini;
import java.awt.Component;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
/**
 *
 * @author xavi
 */
public class MenuJugar extends VistaGenerica {
    
    ControladorDomini controladorDomini;
    ControladorVistes controladorVistes;
    
    /**
     * Constructora que inicialitza els components i afegeix els controladors
     * @param contD
     * @param contV 
     */
    public MenuJugar(ControladorDomini contD, ControladorVistes contV) {
        initComponents();
        controladorDomini = contD;
        controladorVistes = contV;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoGeneraHidato = new javax.swing.JButton();
        botoCarregaHidato = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        botoGeneraHidato.setText("Generar partida aleatoria");
        botoGeneraHidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoGeneraHidatoActionPerformed(evt);
            }
        });

        botoCarregaHidato.setText("Carregar partida");
        botoCarregaHidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCarregaHidatoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Tornar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botoGeneraHidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoCarregaHidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(botoGeneraHidato)
                .addGap(18, 18, 18)
                .addComponent(botoCarregaHidato)
                .addGap(26, 26, 26)
                .addComponent(jToggleButton1)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Mostra la vista generaHidato en cas de que es premi el boto generar
     * partida aleatoria
     * @param evt 
     */
    private void botoGeneraHidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoGeneraHidatoActionPerformed
        controladorVistes.mostraVista("GeneraHidato");
    }//GEN-LAST:event_botoGeneraHidatoActionPerformed
    /**
     * Event que mostra la vista menu en cas de que es premi boto enrere
     * @param evt 
     */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        controladorVistes.mostraVista("Menu");
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    /**
     * Aquest event es encarrega de treure una llista de les partides del usuari
     * i carregarles en cas de que premi ok
     * @param evt 
     */
    private void botoCarregaHidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCarregaHidatoActionPerformed
        // TODO add your handling code here:
        
        List<String> list = controladorDomini.llistatPartides();
        JScrollPane jsp = new JScrollPane();
        JList jlist = new JList(list.toArray());
        
        JOptionPane.showMessageDialog(
                null, 
                jsp = new JScrollPane(jlist), 
                "Carregar Partida",
                1);
        
        if (jlist.getSelectedIndex() != -1) {
            int x = jlist.getSelectedIndex();
            controladorDomini.carregarPartida(list.get(x));
            controladorVistes.mostraVista("vistaJugar");
        }
        
    }//GEN-LAST:event_botoCarregaHidatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoCarregaHidato;
    private javax.swing.JButton botoGeneraHidato;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
