/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistes;
import Domini.Controlador.ControladorDomini;
/**
 *
 * @author xavi
 */
public class MenuJugar extends VistaGenerica {
    
    ControladorDomini controladorDomini;
    ControladorVistes controladorVistes;
    
    /**
     * Creates new form MenuJugar
     */
    
    public MenuJugar(ControladorDomini contD, ControladorVistes contV) {
        initComponents();
        controladorDomini = contD;
        controladorVistes = contV;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoGeneraHidato = new javax.swing.JButton();
        botoCarregaHidato = new javax.swing.JButton();

        botoGeneraHidato.setText("Genera hidato aleatori");
        botoGeneraHidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoGeneraHidatoActionPerformed(evt);
            }
        });

        botoCarregaHidato.setText("Carrega hidato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botoGeneraHidato, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(botoCarregaHidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(botoGeneraHidato)
                .addGap(18, 18, 18)
                .addComponent(botoCarregaHidato)
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botoGeneraHidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoGeneraHidatoActionPerformed
        controladorVistes.mostraVista("GeneraHidato");
    }//GEN-LAST:event_botoGeneraHidatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoCarregaHidato;
    private javax.swing.JButton botoGeneraHidato;
    // End of variables declaration//GEN-END:variables
}
