/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistes;

import Vistes.ControladorVistes;
import Vistes.VistaGenerica;
import Domini.Controlador.ControladorDomini;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
/**
 *
 * @author xavi
 */
public class VistaMenu extends VistaGenerica {
    
    ControladorVistes controladorVistes;
    ControladorDomini controladorDomini;
    /**
     * Creates new form VistaMenu
     */
    public VistaMenu(ControladorDomini contDomini, ControladorVistes contrVistes) {
        initComponents();
        this.controladorVistes = contrVistes;
        controladorDomini = contDomini;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotoJuga = new javax.swing.JButton();
        BotoCarrega = new javax.swing.JButton();
        BotoIntroHidato = new javax.swing.JButton();
        BotoRanking = new javax.swing.JButton();
        BotoLogOut = new javax.swing.JButton();

        BotoJuga.setText("Jugar Partida");
        BotoJuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoJugaActionPerformed(evt);
            }
        });

        BotoCarrega.setText("Carregar Hidato");
        BotoCarrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoCarregaActionPerformed(evt);
            }
        });

        BotoIntroHidato.setText("Introdueix Hidato");
        BotoIntroHidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoIntroHidatoActionPerformed(evt);
            }
        });

        BotoRanking.setText("Rankings");
        BotoRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoRankingActionPerformed(evt);
            }
        });

        BotoLogOut.setText("Log Out");
        BotoLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotoCarrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotoJuga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotoIntroHidato, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(BotoRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotoLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(BotoJuga)
                .addGap(37, 37, 37)
                .addComponent(BotoIntroHidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotoCarrega)
                .addGap(38, 38, 38)
                .addComponent(BotoRanking)
                .addGap(58, 58, 58)
                .addComponent(BotoLogOut)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotoRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotoRankingActionPerformed

    private void BotoLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoLogOutActionPerformed
        
        controladorVistes.mostraVista("Inici");
        
    }//GEN-LAST:event_BotoLogOutActionPerformed

    private void BotoJugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoJugaActionPerformed
        controladorVistes.mostraVista("menuJugar");
    }//GEN-LAST:event_BotoJugaActionPerformed

    private void BotoIntroHidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoIntroHidatoActionPerformed
        controladorVistes.mostraVista("IntrodueixHidato");
    }//GEN-LAST:event_BotoIntroHidatoActionPerformed
    /**
     * Event que s'activa al premer el boto Carrega hidato al menu principal.
     * Mostra un scrollPane de la llista dels hidatos que existeixen.
     * @param evt 
     */
    private void BotoCarregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoCarregaActionPerformed
        // TODO add your handling code here:
        List<String> list = controladorDomini.llistatTaulers();
        JScrollPane jsp = new JScrollPane();
        JList jlist = new JList(list.toArray());
        
        JOptionPane.showMessageDialog(
                null, 
                jsp = new JScrollPane(jlist), 
                "Carregar Hidato",
                1);
        
        if (jlist.getSelectedIndex() != -1) {
            int x = jlist.getSelectedIndex();
            controladorDomini.carregarTauler(list.get(x));
            controladorVistes.mostraVista("vistaJugar");
        }
    }//GEN-LAST:event_BotoCarregaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoCarrega;
    private javax.swing.JButton BotoIntroHidato;
    private javax.swing.JButton BotoJuga;
    private javax.swing.JButton BotoLogOut;
    private javax.swing.JButton BotoRanking;
    // End of variables declaration//GEN-END:variables
}
