/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistes;

/**
 *
 * @author xavi
 */
public class VistaInici extends VistaGenerica {

    /**
     * Creates new form VistaInici
     */
    
    public VistaInici() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoLogIn = new javax.swing.JButton();
        botoRegistrar = new javax.swing.JButton();
        usuariLogIn = new javax.swing.JTextField();
        contrasenyaLogIn = new javax.swing.JTextField();
        usuariRegistrar = new javax.swing.JTextField();
        contrasenyaRegistrar = new javax.swing.JTextField();
        paraulaClau = new javax.swing.JTextField();

        botoLogIn.setText("Log In");
        botoLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoLogInMouseClicked(evt);
            }
        });

        botoRegistrar.setText("Registrar-se");

        usuariLogIn.setText("Usuari");
        usuariLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariLogInMouseClicked(evt);
            }
        });
        usuariLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariLogInActionPerformed(evt);
            }
        });

        contrasenyaLogIn.setText("Contrasenya");

        usuariRegistrar.setText("Usuari");
        usuariRegistrar.setVisible(false);
        usuariRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariRegistrarMouseExited(evt);
            }
        });

        contrasenyaRegistrar.setText("Contrasenya");
        contrasenyaRegistrar.setVisible(false);

        paraulaClau.setText("Paraula clau");
        paraulaClau.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuariRegistrar)
                    .addComponent(contrasenyaRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(paraulaClau)
                    .addComponent(usuariLogIn)
                    .addComponent(contrasenyaLogIn))
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(botoLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasenyaLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasenyaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paraulaClau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usuariLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariLogInActionPerformed

    private void usuariRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariRegistrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariRegistrarMouseExited

    private void usuariLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariLogInMouseClicked
        
    }//GEN-LAST:event_usuariLogInMouseClicked

    private void botoLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoLogInMouseClicked
        usuariLogIn.setVisible(true);
    }//GEN-LAST:event_botoLogInMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoLogIn;
    private javax.swing.JButton botoRegistrar;
    private javax.swing.JTextField contrasenyaLogIn;
    private javax.swing.JTextField contrasenyaRegistrar;
    private javax.swing.JTextField paraulaClau;
    private javax.swing.JTextField usuariLogIn;
    private javax.swing.JTextField usuariRegistrar;
    // End of variables declaration//GEN-END:variables
}
