/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistes;

import Domini.Controlador.ControladorDomini;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author xavi
 */
public class VistaForats extends javax.swing.JPanel {

    /**
     * Creates new form VistaForats
     */
    int numIni;
    int[][] matriu;
    ControladorDomini controladorDomini;
    ControladorVistes controladorVistes;
    JFrame jframe;
    
    public VistaForats(int[][] mat, int num, ControladorDomini contD, ControladorVistes contV, JFrame frame) {
        controladorDomini = contD;
        controladorVistes = contV;
        matriu = mat;
        numIni = num;
        jframe = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotoGenera = new javax.swing.JButton();

        BotoGenera.setText("Genera");
        BotoGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoGeneraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(717, Short.MAX_VALUE)
                .addComponent(BotoGenera)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BotoGenera)
                .addContainerGap(388, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotoGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoGeneraActionPerformed
        boolean resultat = controladorDomini.taulerForats(matriu.length, numIni, matriu);
        if (resultat){
            jframe.setVisible(false);
            controladorVistes.mostraVista("vistaJugar");
        } else {
            JOptionPane.showMessageDialog(null, "Forats incorrectes!", "Atenció", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_BotoGeneraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoGenera;
    // End of variables declaration//GEN-END:variables
}
